baseURL = "https://lpast.github.io/mi_primer_sitio/docs"
languageCode = "en-us"
title = "Mi primer Sitio"
theme = "color-your-world"


#Idioma por defecto
defaultContentLanguage="es"

#Definición de diferentes idiomas
[Languages]
  [Languages.es]
  	title = "Mi primer Sitio"
  	languageName="Español"
  	landingPageURL="https://miprimersitio.org/"
	ContentDir ="content/es"

  [Languages.en]
  	title = "Mi Site"
  	languageName="English"
  	landingPageURL="https://miprimersitio.org/"
	ContentDir ="content/en"

[params]
	name="lorena"
	description="Practica 1 de dwes"
	enableRSS=true

[[menu.main]]
	identifier = "Inicio"
	name="<i class='fas fa-home'></i>Inicio"
	title = "Inicio"
	url = "/inicio/"
	weight = 1
  [[menu.main]]
	identifier = "presentacion"
	name = "presentacion"
	title = "Presentación"
	url = "/presentacion/"
	weight = 2
  [[menu.main]]
	identifier = "DWES01"
	name = "DWES01"
	title = "DWES01"
	url = "/dwes01/"
	weight = 3
[menu]
  [[menu.main]]
	identifier = "Contacto"
	name="Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 4



[social]
twitter="https://www.twitter.com/"
github="https://wwww.github.com/"
 

