baseURL = "https://lpast.github.io/mi_primer_sitio/"
languageCode = "en-us"
title = "Mi primer Sitio"
theme = "color-your-world"


#Idioma por defecto
defaultContentLanguage="es"

#Definición de diferentes idiomas
[Languages]
  [Languages.es]
  	title = "Mi primer Sitio"
  	languageName="Español"
	ContentDir ="content/es"
	weight = 1

[[Languages.es.menu.main]]
	identifier = "Inicio"
	name="<i class='fas fa-home'></i> Inicio"
	title = "Inicio"
	url = "inicio"
	
	weight = 2

[[Languages.es.menu.main]]
	identifier = "presentacion"
	name = "<i class='fas fa-dove'></i> presentacion"
	title = "Presentación"
	url = "presentacion"
	weight = 3
[[Languages.es.menu.main]]
	identifier = "DWES01"
	name = "<i class='fas fa-file-word'></i> DWES01"
	title = "DWES01"
	url = "dwes01"
	weight = 4
[[Languages.es.menu.main]]
	identifier = "Contacto"
	name="<i class='fas fa-address-card'></i> Contacto"
	title = "Contacto"
	url = "contacto"
	weight = 5

  [Languages.en]
  	title = "Mi Site"
  	languageName="English"
	ContentDir ="content/en"
	weight = 2


[[Languages.en.menu.main]]
	identifier = "Home"
	name="<i class='fas fa-home'></i> Home"
	title = "Home"
	url = "home"
	weight = 1
[[Languages.en.menu.main]]
	identifier = "presentation"
	name ="<i class='fas fa-dove'></i> presentation"
	title = "presentation"
	url = "presentation"
	weight = 2
[[Languages.en.menu.main]]
	identifier = "DWES01"
	name = "<i class='fas fa-file-word'></i> DWES01"
	title = "DWES01"
	url = "dwes01"
	weight = 3
[[Languages.en.menu.main]]
	identifier = "Contact"
	name="<i class='fas fa-address-card'></i> Contact"
	title = "Contact"
	url = "contact"
	weight = 4

[params]
	author="lorena m"
	description="Practica 1 de dwes"
	enableRSS=true
	






[social]
twitter="https://www.twitter.com/"
github="https://wwww.github.com/"