baseURL = "http://sitiodelorena.org/"
languageCode = "en-us"
title = "Mi primer Sitio"
theme = "color-your-world"

#Idioma por defecto
defaultContentLanguage="es"

#Definición de diferentes idiomas
[Languages]
  [Languages.es]
  	title = "Mi primer Sitio"
  	languageName="Español"
  	landingPageURL="https://sitiodelorena.org"

  [Languages.en]
  	title = "Mi Site"
  	languageName="Ingles"
  	landingPageURL="https://sitiodelorena.org"
	
[params]
	name="lorena"
	description="Practica 1 de dwes"
	enableRSS=true





[menu]
  [[menu.main]]
	identifier = "Home"
	name="Home"
	title = "Home"
	url = "/home/"
	weight = 1
[[menu.main]]
	identifier = "Inicio"
	name="Inicio"
	title = "Inicio"
	url = "/inicio/"
	weight = 2
  [[menu.main]]
	identifier = "presentacion"
	name = "presentacion"
	title = "Presentación"
	url = "/presentacion/"
	weight = 3
  [[menu.main]]
	identifier = "DWES01"
	name = "DWES01"
	title = "DWES01"
	url = "/dwes01/"
	weight = 4



[social]
twitter="https://www.twitter.com/"
github="https://wwww.github.com/"
 

  
  
